[theme]

# Primary accent color for interactive elements
primaryColor = "#FD78CA"

# Background color for the main content area
backgroundColor = "#FAF7FA"

# Background color used for the sidebar
secondaryBackgroundColor = "#F1EFF2"

textColor = "#000000"

font = "sans serif"
